import os 

# Binance
BINANCE_API_KEY = os.getenv("BINANCE_API_KEY", "Duq52TQKYdrKgZ4qMpHsu5YcPdPbw0Cxreit8G1KpuPVaUFcWI0nwgWjDOZh74ZH")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET", "m1iIffyrCbuznHQQN6KxFkPkG7Fyl5YtZ43XV5DlJAz2okZhhN6Zjksqa03yuEuef")

# Telegram
TELEGRAM_API_TOKEN = os.getenv("TELEGRAM_API_TOKEN", "7663643338:AAHVtqPqkWBE5UwhaBvSPBHU_aznWsFOPPU")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "8156800088")

# Поведение
USE_WATCHLIST_ONLY = True
WATCHLIST = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "AVAXUSDT", "LINKUSDT"]

SCAN_INTERVAL_SEC = 600        # 10 минут
SIGNAL_COOLDOWN_MIN = 30      # 30 минут